export interface TarotCard {
  name: string;
  arcana: "major" | "minor";
  suit?: "wands" | "cups" | "swords" | "pentacles";
  number?: number;
  sequentialIndex: number;
  imagePath: string;
  uprightKeywords: string[];
  reversedKeywords: string[];
  meaning: string;
}

function getImagePath(index: number): string {
  let set: number;
  if (index <= 14) set = 1;
  else if (index <= 30) set = 2;
  else if (index <= 45) set = 3;
  else if (index <= 61) set = 4;
  else set = 5;
  return `/images/tarot/set${set}/${index}.jpg`;
}

export const TAROT_DECK: TarotCard[] = [
  // Major Arcana (22 cards)
  { sequentialIndex: 0, imagePath: getImagePath(0), name: "The Fool", arcana: "major", number: 0, uprightKeywords: ["new beginnings", "innocence", "leap of faith", "spontaneity"], reversedKeywords: ["recklessness", "naivety", "hesitation", "fear of leaping"], meaning: "A leap into the unknown taken with open eyes and an open heart." },
  { sequentialIndex: 1, imagePath: getImagePath(1), name: "The Magician", arcana: "major", number: 1, uprightKeywords: ["manifestation", "willpower", "focus", "skill", "resourcefulness"], reversedKeywords: ["manipulation", "scattered energy", "unused talent", "self-deception"], meaning: "You have everything you need to bring an idea into form." },
  { sequentialIndex: 2, imagePath: getImagePath(2), name: "The High Priestess", arcana: "major", number: 2, uprightKeywords: ["intuition", "mystery", "inner knowing", "stillness"], reversedKeywords: ["blocked intuition", "withdrawal", "ignored knowing"], meaning: "The answer is already inside you. Get quiet enough to hear it." },
  { sequentialIndex: 3, imagePath: getImagePath(3), name: "The Empress", arcana: "major", number: 3, uprightKeywords: ["abundance", "nurturing", "creativity", "generosity"], reversedKeywords: ["smothering", "creative block", "over-giving"], meaning: "Energy that creates, nurtures, and grows what it touches." },
  { sequentialIndex: 4, imagePath: getImagePath(4), name: "The Emperor", arcana: "major", number: 4, uprightKeywords: ["authority", "structure", "leadership", "stability"], reversedKeywords: ["control", "rigidity", "weak authority"], meaning: "Order built through clear vision and firm boundaries." },
  { sequentialIndex: 5, imagePath: getImagePath(5), name: "The Hierophant", arcana: "major", number: 5, uprightKeywords: ["tradition", "spiritual guidance", "mentorship", "learning"], reversedKeywords: ["rebellion", "breaking norms", "dogma rejected"], meaning: "Wisdom passed down through tested structures and teachers." },
  { sequentialIndex: 6, imagePath: getImagePath(6), name: "The Lovers", arcana: "major", number: 6, uprightKeywords: ["love", "harmony", "partnership", "meaningful choice"], reversedKeywords: ["misalignment", "disharmony", "values clash"], meaning: "A meaningful choice anchored in what you truly value." },
  { sequentialIndex: 7, imagePath: getImagePath(7), name: "The Chariot", arcana: "major", number: 7, uprightKeywords: ["determination", "willpower", "victory", "focus"], reversedKeywords: ["lost control", "scattered effort", "stagnation"], meaning: "Force of will moves you through opposing pressures." },
  { sequentialIndex: 8, imagePath: getImagePath(8), name: "Strength", arcana: "major", number: 8, uprightKeywords: ["courage", "inner strength", "patience", "gentle power"], reversedKeywords: ["self-doubt", "weakness", "suppressed power"], meaning: "Power expressed through gentleness and inner steadiness." },
  { sequentialIndex: 9, imagePath: getImagePath(9), name: "The Hermit", arcana: "major", number: 9, uprightKeywords: ["solitude", "introspection", "inner guidance", "wisdom-seeking"], reversedKeywords: ["isolation", "rejection of help", "fear of being seen"], meaning: "Step away from the noise to find your own light." },
  { sequentialIndex: 10, imagePath: getImagePath(10), name: "Wheel of Fortune", arcana: "major", number: 10, uprightKeywords: ["cycles", "change", "luck", "destiny", "turning points"], reversedKeywords: ["bad luck", "resistance to change", "stuck patterns"], meaning: "The turn of fate that asks you to ride the cycle, not stop it." },
  { sequentialIndex: 11, imagePath: getImagePath(11), name: "Justice", arcana: "major", number: 11, uprightKeywords: ["fairness", "truth", "accountability", "integrity"], reversedKeywords: ["unfairness", "dishonesty", "karmic backlog"], meaning: "Truth surfaces. Choices have visible consequences." },
  { sequentialIndex: 12, imagePath: getImagePath(12), name: "The Hanged Man", arcana: "major", number: 12, uprightKeywords: ["surrender", "new perspective", "pause", "willing wait"], reversedKeywords: ["stalling", "martyrdom", "resistance to letting go"], meaning: "Stillness reveals what motion was hiding." },
  { sequentialIndex: 13, imagePath: getImagePath(13), name: "Death", arcana: "major", number: 13, uprightKeywords: ["transformation", "endings", "transition", "rebirth"], reversedKeywords: ["resistance to change", "stagnation", "holding on"], meaning: "An ending that clears space for what wants to begin." },
  { sequentialIndex: 14, imagePath: getImagePath(14), name: "Temperance", arcana: "major", number: 14, uprightKeywords: ["balance", "integration", "patience", "healing"], reversedKeywords: ["imbalance", "excess", "internal disharmony"], meaning: "The quiet alchemy of blending opposites until they harmonize." },
  { sequentialIndex: 15, imagePath: getImagePath(15), name: "The Devil", arcana: "major", number: 15, uprightKeywords: ["attachment", "shadow patterns", "entrapment", "materialism"], reversedKeywords: ["liberation", "breaking free", "reclaiming power"], meaning: "The chains are loose. See them and step out." },
  { sequentialIndex: 16, imagePath: getImagePath(16), name: "The Tower", arcana: "major", number: 16, uprightKeywords: ["sudden change", "upheaval", "revelation", "breakthrough"], reversedKeywords: ["averted disaster", "slow collapse", "delayed truth"], meaning: "A structure built on a false foundation falls so a truer one can rise." },
  { sequentialIndex: 17, imagePath: getImagePath(17), name: "The Star", arcana: "major", number: 17, uprightKeywords: ["hope", "healing", "inspiration", "renewal"], reversedKeywords: ["discouragement", "faith faltering", "hopelessness"], meaning: "After the storm, light returns. Slow, steady, and true." },
  { sequentialIndex: 18, imagePath: getImagePath(18), name: "The Moon", arcana: "major", number: 18, uprightKeywords: ["intuition", "dreams", "illusion", "hidden depths"], reversedKeywords: ["clarity returns", "confusion lifting", "shadow seen"], meaning: "What seems unclear is asking to be felt before it is understood." },
  { sequentialIndex: 19, imagePath: getImagePath(19), name: "The Sun", arcana: "major", number: 19, uprightKeywords: ["joy", "vitality", "success", "clarity", "radiance"], reversedKeywords: ["temporary setback", "dimmed joy", "blocked vitality"], meaning: "Clear, warm, life-giving energy made visible." },
  { sequentialIndex: 20, imagePath: getImagePath(20), name: "Judgement", arcana: "major", number: 20, uprightKeywords: ["awakening", "calling", "reckoning", "rebirth"], reversedKeywords: ["ignored calling", "harsh self-judgment", "missed wake-up call"], meaning: "A clear call to step into a new chapter of your life." },
  { sequentialIndex: 21, imagePath: getImagePath(21), name: "The World", arcana: "major", number: 21, uprightKeywords: ["completion", "integration", "wholeness", "fulfilment"], reversedKeywords: ["incomplete cycles", "lack of closure", "unfinished business"], meaning: "A cycle closes with everything in its proper place." },

  // Minor Arcana - Wands (14)
  { sequentialIndex: 22, imagePath: getImagePath(22), name: "Ace of Wands", arcana: "minor", suit: "wands", number: 1, uprightKeywords: ["inspiration", "new passion", "creative spark", "drive"], reversedKeywords: ["blocked creativity", "hesitation", "missed spark"], meaning: "A fresh creative impulse lights up. Say yes." },
  { sequentialIndex: 23, imagePath: getImagePath(23), name: "Two of Wands", arcana: "minor", suit: "wands", number: 2, uprightKeywords: ["planning", "future vision", "personal power", "choosing direction"], reversedKeywords: ["fear of change", "indecision", "unclear plan"], meaning: "The world is yours to map. Start drawing the lines." },
  { sequentialIndex: 24, imagePath: getImagePath(24), name: "Three of Wands", arcana: "minor", suit: "wands", number: 3, uprightKeywords: ["expansion", "foresight", "exploration", "looking ahead"], reversedKeywords: ["delays", "lack of foresight", "playing too safe"], meaning: "Your effort begins to reach further than you can see." },
  { sequentialIndex: 25, imagePath: getImagePath(25), name: "Four of Wands", arcana: "minor", suit: "wands", number: 4, uprightKeywords: ["celebration", "harmony", "homecoming", "milestones"], reversedKeywords: ["tension at home", "postponed celebration"], meaning: "A moment of arrival. Celebrate before the next chapter." },
  { sequentialIndex: 26, imagePath: getImagePath(26), name: "Five of Wands", arcana: "minor", suit: "wands", number: 5, uprightKeywords: ["conflict", "competition", "struggle", "friction"], reversedKeywords: ["resolution", "end of conflict", "internal struggle"], meaning: "Clashing energies that demand to be worked out." },
  { sequentialIndex: 27, imagePath: getImagePath(27), name: "Six of Wands", arcana: "minor", suit: "wands", number: 6, uprightKeywords: ["victory", "recognition", "success", "momentum"], reversedKeywords: ["ego", "fall from grace", "lack of recognition"], meaning: "A win that others see. And that you have earned." },
  { sequentialIndex: 28, imagePath: getImagePath(28), name: "Seven of Wands", arcana: "minor", suit: "wands", number: 7, uprightKeywords: ["defending position", "standing ground", "perseverance", "courage"], reversedKeywords: ["overwhelm", "giving up", "exhausted defense"], meaning: "Hold your ground. Your position is worth keeping." },
  { sequentialIndex: 29, imagePath: getImagePath(29), name: "Eight of Wands", arcana: "minor", suit: "wands", number: 8, uprightKeywords: ["speed", "swift action", "movement", "news arriving"], reversedKeywords: ["delays", "frustration", "miscommunication"], meaning: "Things move quickly. Be ready for the rush." },
  { sequentialIndex: 30, imagePath: getImagePath(30), name: "Nine of Wands", arcana: "minor", suit: "wands", number: 9, uprightKeywords: ["resilience", "persistence", "last stand", "almost there"], reversedKeywords: ["exhaustion", "paranoia", "refusing rest"], meaning: "One more push. You are closer than you think." },
  { sequentialIndex: 31, imagePath: getImagePath(31), name: "Ten of Wands", arcana: "minor", suit: "wands", number: 10, uprightKeywords: ["burden", "responsibility", "hard work", "overwhelm"], reversedKeywords: ["release", "delegation", "relief"], meaning: "You have taken on too much. Set some of it down." },
  { sequentialIndex: 32, imagePath: getImagePath(32), name: "Page of Wands", arcana: "minor", suit: "wands", uprightKeywords: ["enthusiasm", "exploration", "new ideas", "eager beginner"], reversedKeywords: ["pessimism", "scattered focus", "lack of follow-through"], meaning: "A spark of inspiration arrives. Chase it with curiosity." },
  { sequentialIndex: 33, imagePath: getImagePath(33), name: "Knight of Wands", arcana: "minor", suit: "wands", uprightKeywords: ["action", "adventure", "passion", "charging forward"], reversedKeywords: ["recklessness", "frustration", "burnout"], meaning: "Bold movement that prefers fire to caution." },
  { sequentialIndex: 34, imagePath: getImagePath(34), name: "Queen of Wands", arcana: "minor", suit: "wands", uprightKeywords: ["confidence", "courage", "warmth", "magnetic presence"], reversedKeywords: ["jealousy", "insecurity", "fading inner light"], meaning: "Magnetic, courageous presence that lights up a room." },
  { sequentialIndex: 35, imagePath: getImagePath(35), name: "King of Wands", arcana: "minor", suit: "wands", uprightKeywords: ["visionary leadership", "charisma", "decisiveness", "natural authority"], reversedKeywords: ["impulsiveness", "ego", "all heat no plan"], meaning: "A leader who sees far and acts with conviction." },

  // Minor Arcana - Cups (14)
  { sequentialIndex: 36, imagePath: getImagePath(36), name: "Ace of Cups", arcana: "minor", suit: "cups", number: 1, uprightKeywords: ["new love", "emotional opening", "compassion", "heart awakening"], reversedKeywords: ["blocked emotions", "closed heart", "emptiness"], meaning: "The heart opens. Let what wants to flow, flow." },
  { sequentialIndex: 37, imagePath: getImagePath(37), name: "Two of Cups", arcana: "minor", suit: "cups", number: 2, uprightKeywords: ["partnership", "mutual attraction", "connection", "soul recognition"], reversedKeywords: ["imbalance", "broken connection", "mismatched energy"], meaning: "Two souls meet in mutual recognition." },
  { sequentialIndex: 38, imagePath: getImagePath(38), name: "Three of Cups", arcana: "minor", suit: "cups", number: 3, uprightKeywords: ["friendship", "celebration", "community", "sisterhood"], reversedKeywords: ["gossip", "isolation", "group conflict"], meaning: "Joy multiplied by shared company." },
  { sequentialIndex: 39, imagePath: getImagePath(39), name: "Four of Cups", arcana: "minor", suit: "cups", number: 4, uprightKeywords: ["contemplation", "apathy", "reevaluation", "emotional fatigue"], reversedKeywords: ["awareness returns", "new perspective", "opening to offers"], meaning: "Notice what you have been overlooking." },
  { sequentialIndex: 40, imagePath: getImagePath(40), name: "Five of Cups", arcana: "minor", suit: "cups", number: 5, uprightKeywords: ["grief", "loss", "regret", "focus on what is gone"], reversedKeywords: ["acceptance", "moving on", "healing"], meaning: "Mourn what is gone. Then turn toward what remains." },
  { sequentialIndex: 41, imagePath: getImagePath(41), name: "Six of Cups", arcana: "minor", suit: "cups", number: 6, uprightKeywords: ["nostalgia", "childhood memories", "innocence", "sweetness from past"], reversedKeywords: ["stuck in past", "idealizing memory", "finally moving forward"], meaning: "A sweetness from the past returns to comfort the present." },
  { sequentialIndex: 42, imagePath: getImagePath(42), name: "Seven of Cups", arcana: "minor", suit: "cups", number: 7, uprightKeywords: ["choices", "illusions", "fantasy", "scattered focus"], reversedKeywords: ["clarity", "decision made", "illusions dispelled"], meaning: "Many options. Discern dream from real possibility." },
  { sequentialIndex: 43, imagePath: getImagePath(43), name: "Eight of Cups", arcana: "minor", suit: "cups", number: 8, uprightKeywords: ["walking away", "letting go", "seeking deeper meaning"], reversedKeywords: ["avoidance", "returning to what no longer fits"], meaning: "Leave what has run its course to find what is truer." },
  { sequentialIndex: 44, imagePath: getImagePath(44), name: "Nine of Cups", arcana: "minor", suit: "cups", number: 9, uprightKeywords: ["contentment", "satisfaction", "wishes fulfilled", "emotional fulfilment"], reversedKeywords: ["dissatisfaction", "inner emptiness", "unfulfilled wish"], meaning: "A wish granted. Savour it." },
  { sequentialIndex: 45, imagePath: getImagePath(45), name: "Ten of Cups", arcana: "minor", suit: "cups", number: 10, uprightKeywords: ["emotional fulfilment", "family harmony", "lasting happiness", "soul home"], reversedKeywords: ["family conflict", "disharmony", "surface happiness"], meaning: "The emotional life you have been building has arrived." },
  { sequentialIndex: 46, imagePath: getImagePath(46), name: "Page of Cups", arcana: "minor", suit: "cups", uprightKeywords: ["creative ideas", "intuition", "sensitivity", "messenger of love"], reversedKeywords: ["emotional immaturity", "escapism", "missed message"], meaning: "A tender invitation from the heart. Listen." },
  { sequentialIndex: 47, imagePath: getImagePath(47), name: "Knight of Cups", arcana: "minor", suit: "cups", uprightKeywords: ["romantic", "idealistic", "charm", "following the heart"], reversedKeywords: ["moodiness", "illusion", "charm without substance"], meaning: "A romantic offer arrives. Beautiful and worth examining." },
  { sequentialIndex: 48, imagePath: getImagePath(48), name: "Queen of Cups", arcana: "minor", suit: "cups", uprightKeywords: ["emotional intelligence", "compassion", "intuition", "deeply feeling"], reversedKeywords: ["emotional overwhelm", "codependence", "repressed feelings"], meaning: "The wisdom of someone who feels deeply and holds steady." },
  { sequentialIndex: 49, imagePath: getImagePath(49), name: "King of Cups", arcana: "minor", suit: "cups", uprightKeywords: ["emotional balance", "compassion", "diplomacy", "mature heart"], reversedKeywords: ["emotional manipulation", "volatility", "controlled coldness"], meaning: "Emotional mastery. Feeling everything, acting from centre." },

  // Minor Arcana - Swords (14)
  { sequentialIndex: 50, imagePath: getImagePath(50), name: "Ace of Swords", arcana: "minor", suit: "swords", number: 1, uprightKeywords: ["clarity", "breakthrough", "truth", "decisive insight"], reversedKeywords: ["confusion", "clouded thinking", "dulled insight"], meaning: "A piercing moment of clarity. Name the truth." },
  { sequentialIndex: 51, imagePath: getImagePath(51), name: "Two of Swords", arcana: "minor", suit: "swords", number: 2, uprightKeywords: ["stalemate", "difficult choice", "indecision", "blocked emotions"], reversedKeywords: ["indecision broken", "hard truth faced", "decision finally made"], meaning: "A decision waits. Take off the blindfold." },
  { sequentialIndex: 52, imagePath: getImagePath(52), name: "Three of Swords", arcana: "minor", suit: "swords", number: 3, uprightKeywords: ["heartbreak", "grief", "painful truth", "emotional wound"], reversedKeywords: ["healing begins", "forgiveness", "letting the wound close"], meaning: "Pain that demands to be felt before it can heal." },
  { sequentialIndex: 53, imagePath: getImagePath(53), name: "Four of Swords", arcana: "minor", suit: "swords", number: 4, uprightKeywords: ["rest", "recovery", "contemplation", "mental sabbatical"], reversedKeywords: ["restlessness", "burnout", "refusing rest"], meaning: "Pause. Your mind needs to recover before moving on." },
  { sequentialIndex: 54, imagePath: getImagePath(54), name: "Five of Swords", arcana: "minor", suit: "swords", number: 5, uprightKeywords: ["conflict", "defeat", "ego battles", "hollow victory"], reversedKeywords: ["reconciliation", "moving on from conflict", "peace offered"], meaning: "A win at someone's expense leaves no one whole." },
  { sequentialIndex: 55, imagePath: getImagePath(55), name: "Six of Swords", arcana: "minor", suit: "swords", number: 6, uprightKeywords: ["transition", "moving on", "leaving difficulty behind", "calmer waters"], reversedKeywords: ["stuck in past", "resistance to change", "returning to old waters"], meaning: "Toward calmer waters. The hardest part is behind you." },
  { sequentialIndex: 56, imagePath: getImagePath(56), name: "Seven of Swords", arcana: "minor", suit: "swords", number: 7, uprightKeywords: ["deception", "strategy", "hidden moves", "getting away with something"], reversedKeywords: ["confession", "coming clean", "returning what was taken"], meaning: "Something is being concealed. From you or by you." },
  { sequentialIndex: 57, imagePath: getImagePath(57), name: "Eight of Swords", arcana: "minor", suit: "swords", number: 8, uprightKeywords: ["feeling trapped", "restriction", "self-imposed limits", "mental cage"], reversedKeywords: ["liberation", "releasing limiting beliefs", "walking out of the cage"], meaning: "The cage is mostly in your mind. And you have the key." },
  { sequentialIndex: 58, imagePath: getImagePath(58), name: "Nine of Swords", arcana: "minor", suit: "swords", number: 9, uprightKeywords: ["anxiety", "nightmares", "worry", "3am thoughts"], reversedKeywords: ["hope returns", "fears released", "dawn breaking"], meaning: "3am thoughts that magnify worry. You are safer than your mind says." },
  { sequentialIndex: 59, imagePath: getImagePath(59), name: "Ten of Swords", arcana: "minor", suit: "swords", number: 10, uprightKeywords: ["painful endings", "betrayal", "hitting rock bottom", "the worst is over"], reversedKeywords: ["recovery", "surviving the worst", "dawn after night"], meaning: "The end of something. And the beginning of healing." },
  { sequentialIndex: 60, imagePath: getImagePath(60), name: "Page of Swords", arcana: "minor", suit: "swords", uprightKeywords: ["curiosity", "mental energy", "new ideas", "hunger to learn"], reversedKeywords: ["gossip", "manipulation", "sharp tongue"], meaning: "A fresh, sharp mind ready to learn. Be careful with words." },
  { sequentialIndex: 61, imagePath: getImagePath(61), name: "Knight of Swords", arcana: "minor", suit: "swords", uprightKeywords: ["ambition", "fast thinking", "decisive action", "single-minded focus"], reversedKeywords: ["rashness", "aggression", "charging the wrong target"], meaning: "Move fast. But check your aim." },
  { sequentialIndex: 62, imagePath: getImagePath(62), name: "Queen of Swords", arcana: "minor", suit: "swords", uprightKeywords: ["clear-headed", "independent", "perceptive", "direct"], reversedKeywords: ["cold", "harsh", "bitter", "weaponized clarity"], meaning: "Clarity that cuts through illusion with grace." },
  { sequentialIndex: 63, imagePath: getImagePath(63), name: "King of Swords", arcana: "minor", suit: "swords", uprightKeywords: ["intellectual authority", "truth", "integrity", "mastery of mind"], reversedKeywords: ["tyrannical", "manipulation", "cold logic without heart"], meaning: "A mind that leads with truth and integrity." },

  // Minor Arcana - Pentacles (14)
  { sequentialIndex: 64, imagePath: getImagePath(64), name: "Ace of Pentacles", arcana: "minor", suit: "pentacles", number: 1, uprightKeywords: ["new opportunity", "abundance", "prosperity", "grounded promise"], reversedKeywords: ["missed opportunity", "scarcity mindset", "ungrounded promise"], meaning: "A tangible offer arrives. Take it seriously." },
  { sequentialIndex: 65, imagePath: getImagePath(65), name: "Two of Pentacles", arcana: "minor", suit: "pentacles", number: 2, uprightKeywords: ["balance", "juggling", "adaptability", "dancing with priorities"], reversedKeywords: ["overwhelm", "dropping the ball", "juggling collapse"], meaning: "Balance the many things you are carrying with grace." },
  { sequentialIndex: 66, imagePath: getImagePath(66), name: "Three of Pentacles", arcana: "minor", suit: "pentacles", number: 3, uprightKeywords: ["collaboration", "teamwork", "skill", "recognized expertise"], reversedKeywords: ["lack of teamwork", "ego", "working alone when you should not"], meaning: "Skill multiplied by good collaboration." },
  { sequentialIndex: 67, imagePath: getImagePath(67), name: "Four of Pentacles", arcana: "minor", suit: "pentacles", number: 4, uprightKeywords: ["security", "control", "conservatism", "possessiveness"], reversedKeywords: ["generosity", "loosening grip", "opening the hand"], meaning: "Holding too tightly. Open the hand." },
  { sequentialIndex: 68, imagePath: getImagePath(68), name: "Five of Pentacles", arcana: "minor", suit: "pentacles", number: 5, uprightKeywords: ["hardship", "financial loss", "isolation", "feeling left out in the cold"], reversedKeywords: ["recovery", "support arrives", "finding shelter"], meaning: "Hard times. But there is help nearby if you will see it." },
  { sequentialIndex: 69, imagePath: getImagePath(69), name: "Six of Pentacles", arcana: "minor", suit: "pentacles", number: 6, uprightKeywords: ["generosity", "giving and receiving", "support", "gracious help"], reversedKeywords: ["imbalanced giving", "strings attached", "power dynamics around money"], meaning: "Resources flow. Give and receive in healthy balance." },
  { sequentialIndex: 70, imagePath: getImagePath(70), name: "Seven of Pentacles", arcana: "minor", suit: "pentacles", number: 7, uprightKeywords: ["patience", "long-term investment", "slow growth", "assessment"], reversedKeywords: ["impatience", "lack of growth", "harvest disappointment"], meaning: "Pause and assess. Your work is taking root, even if slowly." },
  { sequentialIndex: 71, imagePath: getImagePath(71), name: "Eight of Pentacles", arcana: "minor", suit: "pentacles", number: 8, uprightKeywords: ["mastery", "skill development", "dedication", "deliberate practice"], reversedKeywords: ["lack of focus", "perfectionism", "mastery without meaning"], meaning: "Steady practice is shaping mastery." },
  { sequentialIndex: 72, imagePath: getImagePath(72), name: "Nine of Pentacles", arcana: "minor", suit: "pentacles", number: 9, uprightKeywords: ["financial independence", "self-sufficiency", "abundance", "earned ease"], reversedKeywords: ["financial setback", "dependence", "loneliness in luxury"], meaning: "The fruits of self-sufficiency. And you have earned them." },
  { sequentialIndex: 73, imagePath: getImagePath(73), name: "Ten of Pentacles", arcana: "minor", suit: "pentacles", number: 10, uprightKeywords: ["legacy", "generational wealth", "family", "lasting foundations"], reversedKeywords: ["family disputes", "lost legacy", "financial instability"], meaning: "Lasting wealth. Material, familial, generational." },
  { sequentialIndex: 74, imagePath: getImagePath(74), name: "Page of Pentacles", arcana: "minor", suit: "pentacles", uprightKeywords: ["ambition", "learning", "new ventures", "the eager apprentice"], reversedKeywords: ["lack of progress", "procrastination", "plans without action"], meaning: "A grounded new venture. Apply yourself and watch it grow." },
  { sequentialIndex: 75, imagePath: getImagePath(75), name: "Knight of Pentacles", arcana: "minor", suit: "pentacles", uprightKeywords: ["hard work", "responsibility", "consistency", "the steady builder"], reversedKeywords: ["laziness", "stagnation", "boredom"], meaning: "Steady hands and a steady plan get you there." },
  { sequentialIndex: 76, imagePath: getImagePath(76), name: "Queen of Pentacles", arcana: "minor", suit: "pentacles", uprightKeywords: ["nurturing", "practical", "abundant", "grounded", "warm provider"], reversedKeywords: ["smothering", "neglect of self", "over-functioning"], meaning: "A warm hearth. Abundance grown from care." },
  { sequentialIndex: 77, imagePath: getImagePath(77), name: "King of Pentacles", arcana: "minor", suit: "pentacles", uprightKeywords: ["wealth", "business success", "stability", "generous leadership"], reversedKeywords: ["greed", "materialism", "status without substance"], meaning: "Earned mastery of the material. Generous because secure." },
];

export function drawRandomCard(): { card: TarotCard; reversed: boolean } {
  const card = TAROT_DECK[Math.floor(Math.random() * TAROT_DECK.length)];
  const reversed = Math.random() > 0.5;
  return { card, reversed };
}
