export const PLANET_IN_SIGN_MEANINGS: Record<
  string,
  Record<string, string>
> = {
  Sun: {
    Aries: "The Sun in Aries is bold, direct, and self-initiating. The collective energy favours action over deliberation right now.",
    Taurus: "The Sun in Taurus is grounded, sensory, and deliberate. The collective energy rewards patience and building over rushing.",
    Gemini: "The Sun in Gemini is curious, communicative, and quick. Ideas are the currency right now.",
    Cancer: "The Sun in Cancer is protective, emotional, and home-oriented. What feels safe matters more than what looks good.",
    Leo: "The Sun in Leo is expressive, generous, and visible. The collective energy wants to be seen doing something meaningful.",
    Virgo: "The Sun in Virgo is precise, service-oriented, and discerning. Detail and craft are where the energy lives.",
    Libra: "The Sun in Libra is relational, fair, and weighing. Decisions benefit from considering both sides before moving.",
    Scorpio: "The Sun in Scorpio is intense, investigative, and deep. Surface answers will not satisfy right now.",
    Sagittarius: "The Sun in Sagittarius is expansive, truth-seeking, and optimistic. The bigger picture is calling.",
    Capricorn: "The Sun in Capricorn is ambitious, structured, and long-game focused. What endures is what matters.",
    Aquarius: "The Sun in Aquarius is innovative, collective-minded, and future-oriented. The group matters as much as the individual.",
    Pisces: "The Sun in Pisces is intuitive, empathic, and fluid. Boundaries between self and other are softer right now.",
  },
  Moon: {
    Aries: "The Moon in Aries brings emotional directness and impatience. Feelings surface fast and pass fast. React less, notice more.",
    Taurus: "The Moon in Taurus brings emotional steadiness and a need for comfort. The body knows what it needs right now.",
    Gemini: "The Moon in Gemini brings emotional curiosity and restlessness. Talking through feelings helps more than sitting with them.",
    Cancer: "The Moon in Cancer is the Moon at home. Emotional sensitivity is heightened. Nurture and be nurtured.",
    Leo: "The Moon in Leo brings a need for recognition and warmth. Generosity feels good today. So does being seen.",
    Virgo: "The Moon in Virgo brings emotional precision. Worry is the shadow. Service and usefulness are the medicine.",
    Libra: "The Moon in Libra brings a need for harmony and fairness. Conflict feels more uncomfortable than usual.",
    Scorpio: "The Moon in Scorpio runs deep. Emotional undercurrents are strong. What is unspoken is louder than what is said.",
    Sagittarius: "The Moon in Sagittarius brings emotional optimism and restlessness. Freedom feels like a need, not a want.",
    Capricorn: "The Moon in Capricorn brings emotional restraint and ambition. Feelings get managed before they get expressed.",
    Aquarius: "The Moon in Aquarius brings emotional detachment and idealism. The collective matters more than the personal right now.",
    Pisces: "The Moon in Pisces brings emotional sensitivity and intuition. The veil between feeling and knowing is thin.",
  },
  Mercury: {
    Aries: "Mercury in Aries thinks fast, speaks first, and asks questions later. Direct communication lands better than subtle hints.",
    Taurus: "Mercury in Taurus thinks slowly and thoroughly. Once a conclusion is reached it holds. Rushing the process costs you.",
    Gemini: "Mercury in Gemini is at home. Ideas multiply, conversations flow, and information moves quickly.",
    Cancer: "Mercury in Cancer thinks with feeling. Gut instinct is data. Emotional intelligence is sharper than logic right now.",
    Leo: "Mercury in Leo communicates with drama and warmth. The story matters as much as the facts.",
    Virgo: "Mercury in Virgo is precise and analytical. The details are where the truth lives right now.",
    Libra: "Mercury in Libra weighs every word. Diplomacy is the default. Saying the hard thing takes extra effort.",
    Scorpio: "Mercury in Scorpio investigates beneath the surface. What is not being said is the most important information.",
    Sagittarius: "Mercury in Sagittarius thinks big and speaks freely. Tact takes effort. Truth takes none.",
    Capricorn: "Mercury in Capricorn is strategic and practical. Only what has a use gets airtime.",
    Aquarius: "Mercury in Aquarius thinks unconventionally. The idea that seems odd is worth taking seriously.",
    Pisces: "Mercury in Pisces thinks in images and feelings rather than logic. Intuition leads. Analysis follows.",
  },
  Venus: {
    Aries: "Venus in Aries loves boldly and impulsively. Attraction is immediate. Patience in love is the growth edge.",
    Taurus: "Venus in Taurus is at home. Pleasure, loyalty, and sensory beauty are what connection looks like right now.",
    Gemini: "Venus in Gemini loves through words and curiosity. Interesting matters as much as attractive.",
    Cancer: "Venus in Cancer loves protectively and deeply. Emotional safety is the foundation of desire.",
    Leo: "Venus in Leo loves dramatically and generously. Grand gestures land. Being chosen publicly matters.",
    Virgo: "Venus in Virgo shows love through service and attention to detail. Acts of care speak louder than words.",
    Libra: "Venus in Libra is at home. Beauty, harmony, and partnership are what the heart wants most.",
    Scorpio: "Venus in Scorpio loves intensely and completely. Half measures are not an option.",
    Sagittarius: "Venus in Sagittarius loves freely and adventurously. Space is an act of love right now.",
    Capricorn: "Venus in Capricorn loves with commitment and long-game thinking. Status and reliability are attractive.",
    Aquarius: "Venus in Aquarius loves unconventionally and values freedom within connection.",
    Pisces: "Venus in Pisces loves with total dissolution of self. Boundaries in love need conscious attention.",
  },
  Mars: {
    Aries: "Mars in Aries is at home. Drive, courage, and direct action are fully activated. The risk is acting before thinking.",
    Taurus: "Mars in Taurus moves slowly but finishes everything it starts. Persistence over speed.",
    Gemini: "Mars in Gemini scatters energy across multiple directions. Focus is the discipline required.",
    Cancer: "Mars in Cancer acts from emotional motivation. The fight is always personal, even when it looks strategic.",
    Leo: "Mars in Leo acts with pride and performance. The audience matters. Pride can be fuel or a trap.",
    Virgo: "Mars in Virgo acts through refinement and service. Efficiency is the highest value.",
    Libra: "Mars in Libra acts through negotiation and fairness. Conflict feels wrong even when it is necessary.",
    Scorpio: "Mars in Scorpio acts with intensity and strategy. Nothing is done halfway. Power dynamics are always present.",
    Sagittarius: "Mars in Sagittarius acts with enthusiasm and optimism. Starting is easy. Finishing takes intention.",
    Capricorn: "Mars in Capricorn acts with ambition and discipline. Long-game wins are the motivation.",
    Aquarius: "Mars in Aquarius acts for the collective. The cause matters more than personal gain.",
    Pisces: "Mars in Pisces acts from intuition and compassion. Boundaries around energy need conscious protection.",
  },
  Jupiter: {
    Aries: "Jupiter in Aries expands through bold initiative and independent action. Risk is rewarded right now.",
    Taurus: "Jupiter in Taurus expands through material abundance and patient building. Slow wealth is real wealth.",
    Gemini: "Jupiter in Gemini expands through learning, communication, and connection. Ideas multiply.",
    Cancer: "Jupiter in Cancer expands through emotional depth, family, and nurturing. What is grown from love flourishes.",
    Leo: "Jupiter in Leo expands through creativity, visibility, and generosity. Shine bigger.",
    Virgo: "Jupiter in Virgo expands through mastery, service, and refinement. Excellence is the path.",
    Libra: "Jupiter in Libra expands through partnership, justice, and beauty. Relationships are the vehicle.",
    Scorpio: "Jupiter in Scorpio expands through transformation, depth, and shared resources. Go deeper.",
    Sagittarius: "Jupiter in Sagittarius is at home. Expansion is natural, optimism is warranted, and truth is the compass.",
    Capricorn: "Jupiter in Capricorn expands through structure, ambition, and long-term commitment.",
    Aquarius: "Jupiter in Aquarius expands through innovation, community, and collective vision.",
    Pisces: "Jupiter in Pisces expands through spiritual depth, compassion, and creative dissolution.",
  },
  Saturn: {
    Aries: "Saturn in Aries disciplines the impulse to act. The lesson is learning when to charge and when to wait.",
    Taurus: "Saturn in Taurus disciplines spending, pleasure, and comfort. Long-term security requires short-term restraint.",
    Gemini: "Saturn in Gemini disciplines communication and thinking. Fewer words, more precision.",
    Cancer: "Saturn in Cancer disciplines emotional expression and vulnerability. Learning to need without apology.",
    Leo: "Saturn in Leo disciplines ego and self-expression. Authentic visibility over performance.",
    Virgo: "Saturn in Virgo disciplines through perfectionism and service. The work itself is the teacher.",
    Libra: "Saturn in Libra disciplines relationships and fairness. Commitment requires real reciprocity.",
    Scorpio: "Saturn in Scorpio disciplines around power, control, and shared resources. What you hold onto holds you.",
    Sagittarius: "Saturn in Sagittarius disciplines beliefs and expansion. Truth needs evidence, not just enthusiasm.",
    Capricorn: "Saturn in Capricorn is at home. Ambition, structure, and long-game discipline are fully supported.",
    Aquarius: "Saturn in Aquarius disciplines innovation and community. Freedom without responsibility is not freedom.",
    Pisces: "Saturn in Pisces disciplines boundaries, escapism, and spiritual life. Grounding the intuitive is the work.",
  },
  Uranus: {
    Aries: "Uranus in Aries disrupts through radical individual action and new beginnings.",
    Taurus: "Uranus in Taurus disrupts financial systems, values, and the relationship with the material world.",
    Gemini: "Uranus in Gemini disrupts communication, technology, and how information moves.",
    Cancer: "Uranus in Cancer disrupts home, family, and what we call security.",
    Leo: "Uranus in Leo disrupts creativity, identity, and how we perform selfhood.",
    Virgo: "Uranus in Virgo disrupts work, health systems, and what efficiency means.",
    Libra: "Uranus in Libra disrupts relationships, partnership structures, and justice systems.",
    Scorpio: "Uranus in Scorpio disrupts power structures, sexuality, and collective transformation.",
    Sagittarius: "Uranus in Sagittarius disrupts belief systems, religion, and how we understand truth.",
    Capricorn: "Uranus in Capricorn disrupts institutions, governments, and what authority looks like.",
    Aquarius: "Uranus in Aquarius is at home. Innovation, collective awakening, and systemic change accelerate.",
    Pisces: "Uranus in Pisces disrupts spiritual frameworks, collective unconscious, and what we cannot see.",
  },
  Neptune: {
    Aries: "Neptune in Aries dissolves the ego and the impulse to act from pure self-interest.",
    Taurus: "Neptune in Taurus dissolves material certainty and what we think we own.",
    Gemini: "Neptune in Gemini dissolves the line between fact and fiction in communication.",
    Cancer: "Neptune in Cancer dissolves family boundaries and the notion of home as fixed.",
    Leo: "Neptune in Leo dissolves ego-driven creativity and performance.",
    Virgo: "Neptune in Virgo dissolves the illusion that perfection is possible or necessary.",
    Libra: "Neptune in Libra dissolves the ideal of perfect partnership and fairness.",
    Scorpio: "Neptune in Scorpio dissolves power structures and the boundary between life and death.",
    Sagittarius: "Neptune in Sagittarius dissolves fixed belief systems and absolute truth.",
    Capricorn: "Neptune in Capricorn dissolves institutional authority and rigid structures.",
    Aquarius: "Neptune in Aquarius dissolves the boundary between individual and collective consciousness.",
    Pisces: "Neptune in Pisces is at home. Spiritual sensitivity, compassion, and dissolution of ego are heightened.",
  },
  Pluto: {
    Aries: "Pluto in Aries transforms through radical rebirth of the self and collective identity.",
    Taurus: "Pluto in Taurus transforms the material world, wealth systems, and the relationship with the Earth.",
    Gemini: "Pluto in Gemini transforms communication, information, and how minds are shaped.",
    Cancer: "Pluto in Cancer transforms family systems, ancestry, and what home means.",
    Leo: "Pluto in Leo transforms creative expression, ego, and generational identity.",
    Virgo: "Pluto in Virgo transforms health systems, work structures, and what service means.",
    Libra: "Pluto in Libra transforms relationship structures, justice, and partnership dynamics.",
    Scorpio: "Pluto in Scorpio is at home. Collective transformation, power, and rebirth are the dominant themes.",
    Sagittarius: "Pluto in Sagittarius transforms belief systems, religion, and collective truth.",
    Capricorn: "Pluto in Capricorn transforms institutions, governments, and corporate power.",
    Aquarius: "Pluto in Aquarius transforms technology, collective consciousness, and social systems.",
    Pisces: "Pluto in Pisces transforms spiritual frameworks and collective unconscious.",
  },
  Chiron: {
    Aries: "Chiron in Aries holds the wound around identity, assertion, and the right to exist as you are.",
    Taurus: "Chiron in Taurus holds the wound around worth, resources, and the right to have what you need.",
    Gemini: "Chiron in Gemini holds the wound around voice, being heard, and the right to be believed.",
    Cancer: "Chiron in Cancer holds the wound around belonging, home, and being nurtured.",
    Leo: "Chiron in Leo holds the wound around being seen, valued, and allowed to shine.",
    Virgo: "Chiron in Virgo holds the wound around being useful, good enough, and worthy of care.",
    Libra: "Chiron in Libra holds the wound around fairness, partnership, and being chosen.",
    Scorpio: "Chiron in Scorpio holds the wound around power, betrayal, and survival.",
    Sagittarius: "Chiron in Sagittarius holds the wound around truth, belief, and the right to seek meaning.",
    Capricorn: "Chiron in Capricorn holds the wound around authority, achievement, and being taken seriously.",
    Aquarius: "Chiron in Aquarius holds the wound around belonging to the collective while remaining individual.",
    Pisces: "Chiron in Pisces holds the wound around spirituality, surrender, and the boundary between self and everything.",
  },
};
